#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
data_dir=$3
passw=$4
current_dir=${PWD}
debian_version=$(lsb_release -c -s)

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a rutorrent
if [[ ! $? -eq 0 ]]; then
  echo "Error: domain/path not available"
  exit 1
fi

# Install sources
#if [ "$debian_version" = "jessie" ]; then
#  cd /tmp
#  wget http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2015.6.1_all.deb
#  sudo dpkg -i deb-multimedia-keyring_2015.6.1_all.deb
  
#  if [ -f /etc/apt/sources.list.d/rutorrent.list ]; then
#    sudo rm /etc/apt/sources.list.d/rutorrent.list
#  fi

#  echo 'deb http://ftp2.fr.debian.org/debian/ jessie main non-free' | sudo tee -a /etc/apt/sources.list.d/rutorrent.list
#  echo 'deb-src http://ftp2.fr.debian.org/debian/ jessie main non-free' | sudo tee -a /etc/apt/sources.list.d/rutorrent.list
#  echo 'deb ftp://ftp.deb-multimedia.org jessie main non-free' | sudo tee -a /etc/apt/sources.list.d/rutorrent.list
#else
#  echo 'deb http://ftp2.fr.debian.org/debian/ wheezy main non-free' | sudo tee -a /etc/apt/sources.list.d/rutorrent.list
#  echo 'deb-src http://ftp2.fr.debian.org/debian/ wheezy main non-free' | sudo tee -a /etc/apt/sources.list.d/rutorrent.list
#fi

# Install de dependencies
sudo apt-get update
sudo apt-get install -y htop automake libcppunit-dev libtool build-essential pkg-config libssl-dev libcurl4-openssl-dev libsigc++-2.0-dev libncurses5-dev screen subversion apache2-utils php5-cli php5-geoip unzip unrar rar zip ffmpeg buildtorrent mediainfo openssl git libcurl4-openssl-devphp5-curl tmux  
# Build xmlrpc
	cd /tmp

	# Download and install xmlrpc-c super-stable
	curl -L http://sourceforge.net/projects/xmlrpc-c/files/Xmlrpc-c%20Super%20Stable/1.33.18/xmlrpc-c-1.33.18.tgz/download -o xmlrpc-c.tgz
	tar zxvf xmlrpc-c.tgz
	mv xmlrpc-c-1.* xmlrpc
	cd xmlrpc
	./configure --disable-cplusplus
	make
	make install

	cd ..
	rm -rv xmlrpc*

	mkdir rtorrent
	cd rtorrent

# Build libtorrent
	curl -L http://rtorrent.net/downloads/libtorrent-0.13.6.tar.gz -o libtorrent.tar.gz
	tar -zxvf libtorrent.tar.gz
	cd libtorrent-0.13.6
	./autogen.sh
	./configure
	make
	make install

	cd ..


# Build rtorrent
	curl -L http://rtorrent.net/downloads/rtorrent-0.9.6.tar.gz -o rtorrent.tar.gz
	tar -zxvf rtorrent.tar.gz
	cd rtorrent-0.9.6
	./autogen.sh
	./configure --with-xmlrpc-c
	make
	make install

	cd ../..
	rm -rv rtorrent

	ldconfig

# Install rutorrent

	curl -L http://dl.bintray.com/novik65/generic/rutorrent-3.6.tar.gz -o rutorrent-3.6.tar.gz
	tar -zxvf rutorrent-3.6.tar.gz

	if [ -d /var/www/html/rutorrent ]; then
		rm -r /var/www/html/rutorrent
	fi

	# Changeing SCGI mount point in rutorrent config.
	sed -i "s/\/RPC2/\/rutorrent\/RPC2/g" ./rutorrent/conf/config.php

	mv -f rutorrent /var/www/html/
	rm -v rutorrent-3.6.tar.gz

	# Changing permissions for rutorrent and plugins.
	chown -R www-data.www-data /var/www/html/rutorrent
	chmod -R 775 /var/www/html/rutorrent



# Configure nginx
sudo sed -i "s@PATHTOCHANGE@$path@g" ../sources/nginx/rutorrent.conf
sudo cp ../sources/nginx/rutorrent.conf /etc/nginx/conf.d/$domain.d/rutorrent.conf

# Create data dir
sudo mkdir $data_dir
sudo mkdir $data_dir/watch
sudo mkdir $data_dir/downloads
sudo mkdir $data_dir/.session

# Create rtorrent user
sudo useradd -p $(openssl passwd -1 $passw) -m rtorrent

# Add rtorrent config
sudo sed -i "s@DATA_DIR@$data_dir@g" ../sources/rtorrent/rtorrent.rc
sudo cp ../sources/rtorrent/rtorrent.rc /home/rtorrent/.rtorrent.rc
sudo chown -R rtorrent:www-data /home/rtorrent/.rtorrent.rc

sudo chown -R rtorrent:www-data $data_dir
sudo chmod 755 $data_dir

# Configure rutorrent
sudo sed -i "s@DATA_DIR@$data_dir@g" ../sources/rutorrent/config.php
sudo cp ../sources/rutorrent/config.php /var/www/rutorrent/conf/config.php
sudo chown -R www-data:www-data /var/www/rutorrent

# Check port availability
sudo yunohost app checkport 45069
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Open port in firewall
sudo yunohost firewall allow TCP 45069 > /dev/null 2>&1

# Launch rtorrent on boot
sudo cp ../sources/init/rtorrent /etc/init.d/rtorrent
sudo chmod +x /etc/init.d/rtorrent
sudo update-rc.d rtorrent defaults

# Start rtorrent
sudo service rtorrent start
sudo yunohost app ssowatconf
sudo service nginx reload

# Save config
sudo yunohost app setting rutorrent data_dir -v $data_dir
sudo yunohost app setting rutorrent path -v $path

# Register the service on yunohost
sudo yunohost service add rtorrent
